#@TYPE: Machine
#@NAME: Voipac i.MX 91 Evaluation Kit
#@SOC: i.MX91
#@DESCRIPTION: Machine configuration for Voipac i.MX 91 EVK
#@MAINTAINER: Marek Belisko <marek.belisko@voipac.com>

MACHINEOVERRIDES =. "imx91-11x11-lpddr4x-evk:"
require conf/machine/imx91-11x11-lpddr4-evk.conf

PREFERRED_PROVIDER_virtual/kernel = "linux-imx"

KERNEL_DEVICETREE = "imx91-voipac-evk.dtb"

UBOOT_CONFIG_BASENAME = "imx91_voipac_evk"

SIGNED_TARGET:mx91-generic-bsp = "flash_singleboot"

KERNEL_DEVICETREE = " \
    freescale/imx91-voipac-evk.dtb \
"

